name = "auth-server-dev"
type = "webpack"

account_id = "00635589a7e41ac9736a417c77b9e364"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-05"

[vars]
ENVIRONMENT = "development"
DATABASE_URL = "postgres://postgres:admin@localhost:5432/bitflix"

[env.production]
name = "auth"
[env.production.vars]
ENVIRONMENT = "production"
