name = "auth"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
webpack_config = "webpack.config.js"
workers_dev = true
compatibility_date = "2022-02-09"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
